# SPDX-FileCopyrightText: 2023-2026 NORCE Research AS
# SPDX-License-Identifier: MIT
# pylint: disable=R0912, R0913, R0914, R0915, R0917

"""
Utiliy functions to write necessary files and variables
"""

import subprocess
from dataclasses import asdict
import numpy as np
from numpy.typing import NDArray
from mako.template import Template

from pyopmspe11.config.config import Config

HEADER = (
    "-- Copyright (C) 2023-2026 NORCE Research AS\n"
    "-- This deck was generated by pyopmspe11 https://github.com/OPM/pyopmspe11\n"
)


def z_c(cfg: Config, y) -> NDArray:
    """Get the corner z coordinate"""
    dy = cfg.dims[1]
    a = (2.0 * y / dy) - 1.0
    return (
        cfg.maxelevation - cfg.elevation * (1.0 - a * a) - (y * cfg.backElevation / dy)
    )


def round_like_e(v: NDArray) -> NDArray:
    """Keep only 8 significant digits to reduce size of created files"""
    return np.asarray([float(f"{x:E}") for x in v])


def create_corner_point_grid(
    cfg: Config, xcoord: NDArray, ycoord: NDArray, zcoord: NDArray
) -> None:
    """Construct COORD and ZCORN"""
    grid = []
    top_z = cfg.dims[2]
    nx, ny, nz = cfg.nxyz
    stride_z = nz + 1
    grid.append("COORD\n")
    x_top = xcoord[::stride_z][: nx + 1]
    x_bot = xcoord[nz::stride_z][: nx + 1]
    xx_top, yy = np.meshgrid(x_top, ycoord, indexing="xy")
    xx_bot, _ = np.meshgrid(x_bot, ycoord, indexing="xy")
    vals = np.column_stack(
        (
            xx_top.ravel(),
            yy.ravel(),
            np.zeros(xx_top.size),
            xx_bot.ravel(),
            yy.ravel(),
            np.zeros(xx_top.size),
        )
    ).ravel()
    grid += compact_format_numeric(round_like_e(vals))
    grid.append("/\n")
    grid.append("ZCORN\n")
    if cfg.spe11 == "spe11c":
        yc = z_c(cfg, ycoord)

        def stream_surface(off: int) -> NDArray:
            zleft = zcoord[off::stride_z][:nx]
            zright = zcoord[off + stride_z :: stride_z][:nx]
            out = [np.empty(0)] * (2 * ny)
            j = 0
            for y in range(ny):
                zb = yc[y]
                zt = yc[y + 1]
                out[j] = np.column_stack((zb + zleft, zb + zright)).ravel()
                out[j + 1] = np.column_stack((zt + zleft, zt + zright)).ravel()
                j += 2
            return round_like_e(np.concatenate(out))

        grid += compact_format_numeric(stream_surface(0))
        for k in range(nz - 1):
            blk = stream_surface(k + 1)
            grid += compact_format_numeric(blk)
            grid += compact_format_numeric(blk)
        out = [np.empty(0)] * (2 * ny)
        j = 0
        for y in range(ny):
            zlow = yc[y] + top_z
            zhigh = yc[y + 1] + top_z
            out[j] = np.repeat([zlow, zlow], nx)
            out[j + 1] = np.repeat([zhigh, zhigh], nx)
            j += 2
        grid += compact_format_numeric(round_like_e(np.concatenate(out)))
    else:
        top = np.column_stack(
            (zcoord[0::stride_z][:nx], zcoord[stride_z::stride_z][:nx])
        ).ravel()
        top = round_like_e(top)
        grid += compact_format_numeric(np.concatenate((top, top)))
        for k in range(1, nz):
            zk = np.column_stack(
                (zcoord[k::stride_z][:nx], zcoord[k + stride_z :: stride_z][:nx])
            ).ravel()
            zk = round_like_e(zk)
            if k == nz - 1:
                grid += compact_format_numeric(np.tile(zk, 3))
            else:
                grid += compact_format_numeric(np.tile(zk, 4))
        final_left = zcoord[(np.arange(nx) + 1) * stride_z - 1]
        final_right = zcoord[(np.arange(nx) + 2) * stride_z - 1]
        final = round_like_e(np.column_stack((final_left, final_right)).ravel())
        grid += compact_format_numeric(np.concatenate((zk, final, final)))
    with open(f"{cfg.deckfol}/GRID.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("".join(grid))
        f.write("/\n")


def write_keywords(
    cfg: Config,
    fipnum: NDArray,
    fluxnum: NDArray,
    xmx: NDArray,
    zmz: NDArray | None = None,
    porv: list | None = None,
) -> None:
    """Write used keywords for OPM Flow"""
    if cfg.spe11 == "spe11a":
        if cfg.grid == "tensor":
            assert zmz is not None
            dx = np.tile(xmx[1:] - xmx[:-1], cfg.nxyz[2])
            dz = np.repeat((zmz[1:] - zmz[:-1])[: cfg.nxyz[2]], cfg.nxyz[0])
            write_keyword(cfg, "DX", dx)
            write_keyword(cfg, "DZ", dz)
    elif cfg.spe11 == "spe11b":
        assert porv is not None
        delta_x = xmx[1:] - xmx[:-1]
        if cfg.grid == "tensor":
            assert zmz is not None
            dx = np.tile(delta_x, cfg.nxyz[2])
            dz = np.repeat((zmz[1:] - zmz[:-1])[: cfg.nxyz[2]], cfg.nxyz[0])
            write_keyword(cfg, "DX", dx)
            write_keyword(cfg, "DZ", dz)
        elif np.min(delta_x) != np.max(delta_x) and cfg.grid == "cartesian":
            cfg.compact_dx = True
            dx = np.concatenate(
                [delta_x, np.tile(delta_x[-cfg.nxyz[0] :], cfg.nxyz[2] - 1)]
            )
            write_keyword(cfg, "DX", dx)
        write_keyword_pv(cfg, porv)
    else:
        assert porv is not None
        write_keyword_pv(cfg, porv)
    write_keyword(cfg, "FIPNUM", fipnum)
    write_keyword(cfg, "FLUXNUM", fluxnum)


def write_keyword_pv(cfg: Config, porv: list) -> None:
    """Write the added pore volume on the boundaries"""
    with open(f"{cfg.deckfol}/PVBOUNDARIES.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("EQUALS\n")
        f.write("\n".join(porv))
        f.write("\n/\n")


def write_keyword(cfg: Config, name: str, values: NDArray) -> None:
    """Write the given keyword"""
    with open(f"{cfg.deckfol}/{name}.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write(f"{name}\n")
        f.write("".join(compact_format_numeric(values)))
        f.write("/\n")


def compact_format_numeric(v: NDArray) -> list:
    """Use the '*' notation to reduce size of created files"""
    change = np.concatenate(([True], v[1:] != v[:-1]))
    idx = np.flatnonzero(change)
    counts = np.diff(np.append(idx, v.size))
    uniq = v[idx]
    out = []
    for val, n in zip(uniq, counts):
        if n > 1:
            if val == 0:
                out.append(f"{n}*0 ")
            elif val.is_integer():
                out.append(f"{n}*{int(val)} ")
            else:
                out.append(f"{n}*{val} ")
        else:
            if val == 0:
                out.append("0 ")
            elif val.is_integer():
                out.append(f"{int(val)} ")
            else:
                out.append(f"{val} ")
    return out


def opm_files(cfg: Config) -> None:
    """Write opm-related files by running mako templates"""
    mytemplate = Template(filename=f"{cfg.pat}/templates/co2/{cfg.spe11}.mako")
    filledtemplate = mytemplate.render(dic=asdict(cfg))
    with open(
        f"{cfg.deckfol}/{cfg.fol.split('/')[-1].upper()}.DATA", "w", encoding="utf8"
    ) as file:
        file.write(filledtemplate)
    mytemplate = Template(
        filename=f"{cfg.pat}/templates/common/saturation_functions.mako"
    )
    filledtemplate = mytemplate.render(dic=asdict(cfg))
    script = f"{cfg.deckfol}/saturation_functions.py"
    with open(script, "w", encoding="utf8") as file:
        file.write(filledtemplate)
    subprocess.run(["chmod", "u+x", script], check=True)
    result = subprocess.run(["python3", script], check=True)
    if result.returncode != 0:
        raise ValueError(f"Invalid result: {result.returncode}")
    subprocess.run(["rm", "-rf", script], check=True)


def write_regular_spe11c_grid(
    cfg: Config, xmx: NDArray, ymy: NDArray, zmz: NDArray
) -> None:
    """Write structured SPE11C grid"""
    grid = []
    grid.append("COORD\n")
    xx, yy = np.meshgrid(xmx, ymy, indexing="xy")
    grid += compact_format_numeric(
        round_like_e(
            np.column_stack(
                (
                    xx.ravel(),
                    yy.ravel(),
                    np.zeros(xx.size),
                    xx.ravel(),
                    yy.ravel(),
                    np.zeros(xx.size),
                )
            ).ravel()
        )
    )
    grid.append("/\n")
    grid.append("ZCORN\n")
    nx, ny, nz = cfg.nxyz
    z_base = z_c(cfg, ymy)
    out = []
    for y in range(ny):
        zb = z_base[y]
        zt = z_base[y + 1]
        out.append(np.repeat([zb, zb], nx))
        out.append(np.repeat([zt, zt], nx))
    grid += compact_format_numeric(round_like_e(np.concatenate(out)))
    for k in range(nz - 1):
        shift = zmz[k + 1]
        out = []
        for y in range(ny):
            zb = z_base[y] + shift
            zt = z_base[y + 1] + shift
            out.append(np.repeat([zb, zb], nx))
            out.append(np.repeat([zt, zt], nx))
        blk = round_like_e(np.concatenate(out))
        grid += compact_format_numeric(np.tile(blk, 2))
    final_shift = cfg.dims[2]
    out = []
    for y in range(ny):
        zb = z_base[y] + final_shift
        zt = z_base[y + 1] + final_shift
        out.append(np.repeat([zb, zb], nx))
        out.append(np.repeat([zt, zt], nx))
    grid += compact_format_numeric(round_like_e(np.concatenate(out)))
    with open(f"{cfg.deckfol}/GRID.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("".join(grid))
        f.write("/\n")
