name: macOS

on:
 push:
   branches:
     - main
   
jobs:
  run-pyopmspe11-macos:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 90
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install OPM Flow
      run: |
        brew install cssr-tools/opm/opm-simulators

    - name: Install python requirements
      run: |
        python3 -m venv vpyopmspe11
        . vpyopmspe11/bin/activate
        echo "$PWD/vpyopmspe11/bin" >> $GITHUB_PATH
        pip install --upgrade pip setuptools wheel
        pip install -e .
        pip install -r dev-requirements.txt

    - name: Run a simple example using pyopmspe11
      run: |
        pyopmspe11 -i examples/spe11b.toml -o spe11b -m deck_flow -f 0

    - name: Check if the example run
      run: |
        file="${{ github.workspace }}/spe11b/SPE11B.UNRST"
        if [ -f "$file" ]; then
          echo "pyopmspe11 succeeded"
        else
          echo "pyopmspe11 failed"
          exit 1
        fi
